# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               My Tech Blog.
tagline:             ''
description:         'Tomaž Kovačič about technology and engineering.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0


gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
